# **Payments Service**
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: openjdk:8-jdk-alpine
        command: ["java", "-jar", "-Dserver.port=8081", "application.jar"]
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    type: ClusterIP
